/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bridge-table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bridge Table
         * @description Create a bridge table using RS-JP or CS-JP-LP algorithm.
         *
         *     This endpoint finds the best matches for each value in list_r from list_s
         *     based on corpus co-occurrence data.
         *
         *     - RS-JP (row): Independent per-row optimization. Returns top_k candidates per R value.
         *       Each R value independently picks its best S matches based on pairwise NPMI scores.
         *
         *     - CS-JP-LP (column): Global optimization considering all rows together.
         *       Returns ONE optimal complete mapping that maximizes aggregate column-level PMI scores.
         *       The top_k parameter is ignored for this method.
         *
         *     Args:
         *         request_data: BridgeTableRequest containing:
         *             - list_r: values to be matched
         *             - list_s: candidate values
         *             - join_method: "row" for RS-JP or "column" for CS-JP-LP
         *             - top_k: number of candidates per row (RS-JP only, ignored for CS-JP-LP)
         *         request: FastAPI request object to access app state
         *
         *     Returns:
         *         BridgeTableResponse with the best matches.
         *         - For RS-JP: top_k matches per R value (can have multiple rows per R value)
         *         - For CS-JP-LP: one match per R value (optimal global mapping)
         *
         *     Raises:
         *         HTTPException: If the operation fails
         */
        post: operations["create_bridge_table_bridge_table_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/join-from-bridge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join From Bridge
         * @description Perform semantic join using uploaded tables and bridge table.
         */
        post: operations["join_from_bridge_join_from_bridge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Return recent join history from the application DB.
         *
         *     If the application DB is not configured or an error occurs, an empty
         *     list is returned (or a 500 is raised on serious errors).
         */
        get: operations["get_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{history_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History Detail
         * @description Return a single history entry including the stored table bodies.
         *
         *     The response includes only the bodies of the stored tables (list of rows),
         *     not the stored column metadata.
         */
        get: operations["get_history_detail_history__history_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/recommend-columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Columns
         * @description Get AI recommendations for which columns to join.
         */
        post: operations["recommend_columns_ai_recommend_columns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Ai Status
         * @description Check if Ollama is running and which models are available.
         */
        get: operations["check_ai_status_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/recommend-bridge-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Bridge Entries
         * @description Get AI recommendations for which bridge entries to use.
         */
        post: operations["recommend_bridge_entries_ai_recommend_bridge_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Table */
        post: operations["upload_table_tables_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tables */
        get: operations["get_tables_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Table */
        get: operations["get_table_tables__table_id__get"];
        put?: never;
        post?: never;
        /** Delete Table Endpoint */
        delete: operations["delete_table_endpoint_tables__table_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIBridgeRecommendation
         * @description AI recommendation for which S value to use for an R value.
         */
        AIBridgeRecommendation: {
            /**
             * R Val
             * @description Value from R
             */
            r_val: string;
            /**
             * Recommended S Val
             * @description Recommended S value for this R value
             */
            recommended_s_val: string;
            /**
             * Reason
             * @description Why this S value was recommended
             */
            reason: string;
            /**
             * Confidence
             * @description Confidence in this recommendation
             */
            confidence: number;
        };
        /**
         * AIBridgeRecommendationRequest
         * @description Request for AI bridge entry recommendations.
         * @example {
         *       "bridge_entries": [
         *         {
         *           "npmi": 0.9,
         *           "r_val": "Germany",
         *           "s_val": "DE"
         *         },
         *         {
         *           "npmi": 0.7,
         *           "r_val": "Germany",
         *           "s_val": "GE"
         *         },
         *         {
         *           "npmi": 0.5,
         *           "r_val": "Germany",
         *           "s_val": "GER"
         *         },
         *         {
         *           "npmi": 0.95,
         *           "r_val": "UK",
         *           "s_val": "GB"
         *         },
         *         {
         *           "npmi": 0.8,
         *           "r_val": "UK",
         *           "s_val": "UK"
         *         }
         *       ]
         *     }
         */
        AIBridgeRecommendationRequest: {
            /**
             * Bridge Entries
             * @description RS-JP top-k results with r_val, s_val, npmi fields
             * @example [
             *       {
             *         "npmi": 0.9,
             *         "r_val": "Germany",
             *         "s_val": "DE"
             *       },
             *       {
             *         "npmi": 0.7,
             *         "r_val": "Germany",
             *         "s_val": "GE"
             *       },
             *       {
             *         "npmi": 0.95,
             *         "r_val": "UK",
             *         "s_val": "GB"
             *       }
             *     ]
             */
            bridge_entries: {
                [key: string]: unknown;
            }[];
        };
        /**
         * AIBridgeRecommendationResponse
         * @description AI recommendations for bridge entries.
         */
        AIBridgeRecommendationResponse: {
            /**
             * Recommendations
             * @description Recommended S value for each R value
             */
            recommendations: components["schemas"]["AIBridgeRecommendation"][];
            /**
             * Analysis
             * @description Overall reasoning for the recommendations
             */
            analysis: string;
            /**
             * Recommended Indices
             * @description Indices of recommended entries in the original bridge_entries array
             */
            recommended_indices: number[];
            /**
             * Model Used
             * @description Name of AI model used
             */
            model_used: string;
        };
        /**
         * AIColumnMatchRequest
         * @description Request model for AI-powered column matching.
         * @example {
         *       "max_samples": 100,
         *       "table_r": [
         *         {
         *           "country_code": "US",
         *           "id": 1,
         *           "population": 331000000
         *         },
         *         {
         *           "country_code": "UK",
         *           "id": 2,
         *           "population": 67000000
         *         },
         *         {
         *           "country_code": "FR",
         *           "id": 3,
         *           "population": 67000000
         *         }
         *       ],
         *       "table_s": [
         *         {
         *           "continent": "North America",
         *           "country_name": "United States"
         *         },
         *         {
         *           "continent": "Europe",
         *           "country_name": "United Kingdom"
         *         },
         *         {
         *           "continent": "Europe",
         *           "country_name": "France"
         *         }
         *       ]
         *     }
         */
        AIColumnMatchRequest: {
            /**
             * Table R
             * @description First table as list of records
             * @example [
             *       {
             *         "country_code": "US",
             *         "id": 1,
             *         "population": 331000000
             *       },
             *       {
             *         "country_code": "UK",
             *         "id": 2,
             *         "population": 67000000
             *       }
             *     ]
             */
            table_r: {
                [key: string]: unknown;
            }[];
            /**
             * Table S
             * @description Second table as list of records
             * @example [
             *       {
             *         "continent": "North America",
             *         "country_name": "United States"
             *       },
             *       {
             *         "continent": "Europe",
             *         "country_name": "United Kingdom"
             *       }
             *     ]
             */
            table_s: {
                [key: string]: unknown;
            }[];
            /**
             * Max Samples
             * @description Maximum number of rows to analyze from each table (default: 100)
             * @default 100
             */
            max_samples: number;
        };
        /**
         * AIColumnRecommendation
         * @description AI recommendation for which columns to join.
         */
        AIColumnRecommendation: {
            /**
             * R Column
             * @description Column name from table R
             */
            r_column: string;
            /**
             * S Column
             * @description Column name from table S
             */
            s_column: string;
            /**
             * Confidence
             * @description Confidence score between 0.0 and 1.0
             */
            confidence: number;
            /**
             * Reason
             * @description Explanation for why these columns should be joined
             */
            reason: string;
        };
        /**
         * AIColumnRecommendationResponse
         * @description AI-powered column join recommendations.
         * @example {
         *       "analysis": "Table R contains country data with ISO codes, while Table S has full country names. These can be semantically joined.",
         *       "model_used": "mistral",
         *       "recommendations": [
         *         {
         *           "confidence": 0.92,
         *           "r_column": "country_code",
         *           "reason": "country_code contains abbreviations that semantically match country_name full names",
         *           "s_column": "country_name"
         *         }
         *       ],
         *       "rows_analyzed_r": 100,
         *       "rows_analyzed_s": 100,
         *       "table_r_columns": [
         *         "id",
         *         "country_code",
         *         "population"
         *       ],
         *       "table_s_columns": [
         *         "country_name",
         *         "continent"
         *       ]
         *     }
         */
        AIColumnRecommendationResponse: {
            /**
             * Recommendations
             * @description List of recommended column join pairs
             */
            recommendations: components["schemas"]["AIColumnRecommendation"][];
            /**
             * Analysis
             * @description Overall analysis of the table relationship
             */
            analysis: string;
            /**
             * Model Used
             * @description Name of the AI model used for analysis
             */
            model_used: string;
            /**
             * Table R Columns
             * @description Column names from table R
             */
            table_r_columns: string[];
            /**
             * Table S Columns
             * @description Column names from table S
             */
            table_s_columns: string[];
            /**
             * Rows Analyzed R
             * @description Number of rows analyzed from table R
             */
            rows_analyzed_r: number;
            /**
             * Rows Analyzed S
             * @description Number of rows analyzed from table S
             */
            rows_analyzed_s: number;
        };
        /**
         * AIOllamaStatus
         * @description Ollama AI service status.
         */
        AIOllamaStatus: {
            /**
             * Ollama Running
             * @description Whether Ollama service is running
             */
            ollama_running: boolean;
            /**
             * Model Requested
             * @description Model requested for use
             */
            model_requested?: string | null;
            /**
             * Model Available
             * @description Whether the requested model is available
             */
            model_available?: boolean | null;
            /**
             * Available Models
             * @description List of available model names
             */
            available_models?: string[] | null;
            /**
             * Error
             * @description Error message if Ollama is not running
             */
            error?: string | null;
            /**
             * Recommendation
             * @description Recommendation for fixing the issue
             */
            recommendation?: string | null;
        };
        /** Body_upload_table_tables_upload_post */
        Body_upload_table_tables_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * BridgeTableEntry
         * @description Single entry in the bridge table showing a candidate match.
         */
        BridgeTableEntry: {
            /**
             * R Val
             * @description Value from list R
             */
            r_val: string;
            /**
             * S Val
             * @description Candidate value from list S
             */
            s_val: string;
            /**
             * Npmi
             * @description Score for this match. RS-JP: single pairwise NPMI score. CS-JP-LP: aggregate column-level PMI score (sum).
             */
            npmi: number | null;
        };
        /**
         * BridgeTableRequest
         * @description Request model for creating a bridge table.
         * @example {
         *       "join_method": "row",
         *       "list_r": [
         *         "US",
         *         "UK",
         *         "DE"
         *       ],
         *       "list_s": [
         *         "USA",
         *         "United Kingdom",
         *         "Germany"
         *       ],
         *       "top_k": 5
         *     }
         */
        BridgeTableRequest: {
            /**
             * List R
             * @description First list of strings (R set)
             * @example [
             *       "US",
             *       "UK",
             *       "DE"
             *     ]
             */
            list_r: string[];
            /**
             * List S
             * @description Second list of strings (S set)
             * @example [
             *       "USA",
             *       "United Kingdom",
             *       "Germany"
             *     ]
             */
            list_s: string[];
            /**
             * Join Method
             * @description Join algorithm: 'row' for RS-JP or 'column' for CS-JP-LP
             * @default row
             * @example row
             * @enum {string}
             */
            join_method: "row" | "column";
            /**
             * Top K
             * @description Number of top candidates to return per R value (RS-JP only). Ignored for CS-JP-LP which always returns one optimal complete mapping.
             * @default 1
             * @example 5
             */
            top_k: number;
        };
        /**
         * BridgeTableResponse
         * @description Response model for bridge table creation.
         * @example {
         *       "bridge_table": [
         *         {
         *           "npmi": 5.32,
         *           "r_val": "US",
         *           "s_val": "USA"
         *         },
         *         {
         *           "npmi": 4.81,
         *           "r_val": "US",
         *           "s_val": "United States"
         *         },
         *         {
         *           "npmi": 6.12,
         *           "r_val": "UK",
         *           "s_val": "United Kingdom"
         *         }
         *       ],
         *       "total_candidates": 3,
         *       "total_r_values": 2,
         *       "total_s_values": 3
         *     }
         */
        BridgeTableResponse: {
            /**
             * Bridge Table
             * @description Best match for each R value (highest PMI score)
             */
            bridge_table: components["schemas"]["BridgeTableEntry"][];
            /**
             * Total R Values
             * @description Total number of values in list R
             */
            total_r_values: number;
            /**
             * Total S Values
             * @description Total number of values in list S
             */
            total_s_values: number;
            /**
             * Total Candidates
             * @description Total number of matches found (one per R value)
             */
            total_candidates: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryDetailEntry */
        HistoryDetailEntry: {
            /**
             * Id
             * @description Unique history record id
             */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             * @description When the join was created
             */
            timestamp: string;
            /**
             * R Join Col
             * @description Join column used for R
             */
            r_join_col: string;
            /**
             * S Join Col
             * @description Join column used for S
             */
            s_join_col: string;
            /**
             * List R
             * @description Body of the stored R table
             */
            list_r: {
                [key: string]: unknown;
            }[];
            /**
             * List S
             * @description Body of the stored S table
             */
            list_s: {
                [key: string]: unknown;
            }[];
            /**
             * Bridge Table
             * @description Body of the stored bridge table
             */
            bridge_table: {
                [key: string]: unknown;
            }[];
            /**
             * Result
             * @description Body of the stored result table
             */
            result: {
                [key: string]: unknown;
            }[];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /**
             * Id
             * @description Unique history record id
             */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             * @description When the join was created
             */
            timestamp: string;
            /**
             * R Join Col
             * @description Join column used for R
             */
            r_join_col: string;
            /**
             * S Join Col
             * @description Join column used for S
             */
            s_join_col: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /**
             * Entries
             * @description List of saved join operations
             */
            entries: components["schemas"]["HistoryEntry"][];
        };
        /**
         * JoinResponse
         * @description Response model for the three-way semantic join endpoint.
         * @example {
         *       "matched_count": 2,
         *       "result": [
         *         {
         *           "country_code": "US",
         *           "country_name": "USA",
         *           "id": 1,
         *           "pmi": 5.32,
         *           "population": 331000000,
         *           "r_val": "US",
         *           "s_val": "USA"
         *         },
         *         {
         *           "country_code": "UK",
         *           "country_name": "United Kingdom",
         *           "id": 2,
         *           "pmi": 6.12,
         *           "population": 67000000,
         *           "r_val": "UK",
         *           "s_val": "United Kingdom"
         *         }
         *       ],
         *       "total_r_records": 2,
         *       "total_records": 2
         *     }
         */
        JoinResponse: {
            /**
             * Result
             * @description List of joined records (R JOIN bridge JOIN S)
             */
            result: {
                [key: string]: unknown;
            }[];
            /**
             * Total Records
             * @description Total number of records in the result
             */
            total_records: number;
            /**
             * Total R Records
             * @description Total number of records in list R
             */
            total_r_records: number;
            /**
             * Matched Count
             * @description Number of R records that found a match in S
             */
            matched_count: number;
        };
        /**
         * JoinWithBridgeRequest
         * @description Request model for three-way join using table IDs from database.
         * @example {
         *       "bridge_table": [
         *         {
         *           "pmi": 5.32,
         *           "r_val": "US",
         *           "s_val": "USA"
         *         },
         *         {
         *           "pmi": 6.12,
         *           "r_val": "UK",
         *           "s_val": "United Kingdom"
         *         }
         *       ],
         *       "r_join_col": "country_code",
         *       "s_join_col": "country_name",
         *       "table_r_id": 1,
         *       "table_s_id": 2
         *     }
         */
        JoinWithBridgeRequest: {
            /**
             * Table R Id
             * @description ID of uploaded table R from database
             * @example 1
             */
            table_r_id: number;
            /**
             * R Join Col
             * @description Column name in table R to join with bridge table r_val
             * @example country_code
             */
            r_join_col: string;
            /**
             * Bridge Table
             * @description Pre-computed bridge table with candidates and PMI scores
             */
            bridge_table: components["schemas"]["BridgeTableEntry"][];
            /**
             * Table S Id
             * @description ID of uploaded table S from database
             * @example 2
             */
            table_s_id: number;
            /**
             * S Join Col
             * @description Column name in table S to join with bridge table s_val
             * @example country_name
             */
            s_join_col: string;
        };
        /**
         * TablesListResponse
         * @description Response listing all uploaded tables.
         */
        TablesListResponse: {
            /** Tables */
            tables: components["schemas"]["UploadedTableMetadata"][];
            /** Total */
            total: number;
        };
        /**
         * UploadTableResponse
         * @description Response after uploading a table.
         */
        UploadTableResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Message */
            message: string;
        };
        /**
         * UploadedTableDetail
         * @description Full uploaded table including body data.
         */
        UploadedTableDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Upload Timestamp */
            upload_timestamp: string;
            /** Columns */
            columns: string[];
            /** Row Count */
            row_count: number;
            /** Body */
            body: {
                [key: string]: unknown;
            }[];
        };
        /**
         * UploadedTableMetadata
         * @description Metadata about an uploaded table (without body data).
         */
        UploadedTableMetadata: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Upload Timestamp */
            upload_timestamp: string;
            /** Columns */
            columns: string[];
            /** Row Count */
            row_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_bridge_table_bridge_table_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BridgeTableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_from_bridge_join_from_bridge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWithBridgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    get_history_detail_history__history_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                history_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetailEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_columns_ai_recommend_columns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIColumnMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIColumnRecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_ai_status_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIOllamaStatus"];
                };
            };
        };
    };
    recommend_bridge_entries_ai_recommend_bridge_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIBridgeRecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIBridgeRecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_table_tables_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_table_tables_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tables_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesListResponse"];
                };
            };
        };
    };
    get_table_tables__table_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedTableDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_table_endpoint_tables__table_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
